apiVersion: v1
kind: Service
metadata:
  name: lanchat-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.240
  ports:
  - name: inspircd
    protocol: TCP
    port: 6667
    targetPort: "inspircd-port"
  - name: thelounge
    protocol: TCP
    port: 80
    targetPort: "thelounge-port"
  selector:
    lbType: external